pysched:
	virtualenv -p python2 pysched
	pysched/bin/pip install --upgrade pip
	pysched/bin/pip install -r requirements.txt	

deploy:
	mkdir -p /var/www/html/webtune_live
	rm -rf /var/www/html/webtune_live/{js,css,manifest*,tuner.html}
	cp -r js css tuner.html /var/www/html/webtune_live/
	cp favicon.ico /var/www/html/
